services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    command: >
      bash -c "rabbitmq-server"

  nhl-game-monitor:
    build:
      context: ../nhl-game-monitor-net/nhl-game-monitor
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "5000:8080"
