spring:
  application:
    name: nhl-stats-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: password
    listener:
      simple:
        auto-startup: true
    dynamic: false
  elasticsearch:
    uris: http://opensearch:9200

opensearch:
  uris: http://opensearch:9200

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

infrastructure:
  services:
    dotnet-monitor:
      name: nhl-game-monitor
      health-url: http://nhl-game-monitor:8080/health
