spring:
  application:
    name: nhl-stats-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: password
    listener:
      simple:
        auto-startup: true
    dynamic: false

opensearch:
  uris: http://opensearch:9200

server:
  port: 8080
